name: build

on:
  push:
    branches:
      - main
  pull_request:

env:
  TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  test:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13, windows-latest]
    permissions:
      # required for all workflows
      security-events: write
    steps:
    - name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
    - name: Set up Go
      uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe #v4.1.0
      with:
        go-version-file: 'go.mod'
    - name: Initialize CodeQL
      uses: github/codeql-action/init@28deaeda66b76a05916b6923827895f2b14ab387 # v3.28.16
      with:
        languages: go
    - name: Run build
      run: go build github.com/lonegunmanb/newres/v3
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@28deaeda66b76a05916b6923827895f2b14ab387 # v3.28.16
    - name: Run tests
      run: go test -v github.com/lonegunmanb/newres/v3/pkg
    - name: Run Gosec Security Scanner
      uses: securego/gosec@d4617f51baf75f4f809066386a4f9d27b3ac3e46 #v2.21.4
      if: runner.os == 'Linux'
